#!/bin/bash

echo "🚀 MCP Registry App - GitHub Publication Script"
echo "=============================================="
echo ""
echo "Step 1: Create a new repository on GitHub"
echo "- Go to: https://github.com/new"
echo "- Repository name: mcp-registry-app"
echo "- Description: A modern web application for searching and exploring Model Context Protocol (MCP) servers"
echo "- Make it Public"
echo "- Don't initialize with README"
echo "- Click 'Create repository'"
echo ""
echo "Step 2: After creating the repo, replace YOUR_USERNAME below and run:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/mcp-registry-app.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Or if you want to use SSH:"
echo "git remote add origin git@github.com:YOUR_USERNAME/mcp-registry-app.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "✅ Your repository is ready with:"
echo "- Complete source code"
echo "- Professional README"
echo "- MIT License"
echo "- Clean .gitignore"
echo "- Proper commit history"
